### ISSUE TITLE
Do we need to include smkoking status for household member information?

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/bmgf-maps#6]

**Comment by fannymawbey** [comment]
Answered in another thread.

**Comment by rbroth** [comment]
> Answered in another thread.

link?

**Comment by fannymawbey** [comment]
Are you testing my GitHub abilities?

https://github.com/micronutrientsupport/bmgf-maps/issues/3

**Comment by rbroth** [comment]
perhaps 😛 

But also, it's a good habit to get into in order to keep all information relevant to an issue together and easily accessible. Imagine, for example, if another developer wanted to work on this issue but had to search through hundreds of other issues for the answer.

**Comment by rbroth** [comment]
For the record, the answer is "No"
