### ISSUE TITLE
Demographic groups for biomarker data

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/bmgf-maps#7]
What are the possible groups? Women of reproductive age, pregnant; Women of reproductive age, not-pregnant; etc.

What other demographic data is included biomarker data?

**Comment by fannymawbey** [comment]
**Women of reproductive age (pregnant and non pregnant)**
Non-Pregnant women of reproductive age
Pregnant women of reproductive age
Lactating women
**Preschool children (0-59months) or 6-59months**
School children (6-14Y)
Adolescents (girls and boys together or separately)
50Y and older
Men

Most frequent in bold

**Comment by rbroth** [comment]
Are these demographic groups well-defined? E.g. are all female people aged 15–44 defined as "woman of reproductive age"? Will the data include actual age data for each person? I'm asking because it looks like we could derive these categories ourselves as long as we had the following data for each person:

- age
- sex
- lactating yes/no
- pregnant yes/no

**Comment by fannymawbey** [comment]
Yes we have information on the age.
The groups above mean that the survey has been designed to have enough participants belonging to this demographic group to be able to give an estimate for this group.

For example, if a survey has one group 'women of reproductive age (pregnant or non pregnant)' -> it means you will have a group of women, some might be pregnant, and you could end up with 1 or 50 pregnant women. 

If a survey has 2 groups: 'pregnant women of reproductive age' and 'non pregnant women of reproductive age', it means that you have a minimum sample size for these 2 groups.

Does that make sense? Happy to share an extract of a micronutrient survey survey design if that can help?

Fanny

**Comment by rbroth** [comment]
Will we always have data for the individual persons? Or is some of the data that we will receive pre-aggregated?

 Yes, an example would be ideal

**Comment by fannymawbey** [comment]
You have all the data per individual.

[Malawi NOT secure.pdf](https://github.com/micronutrientsupport/bmgf-maps/files/5355024/Malawi.NOT.secure.pdf)

If you look at this micronutrient report, pages 16 and 14, you will see the different demographic groups and the calculated sample size for each group.

**Comment by rbroth** [comment]
Ok, if there's no other demographic data needed I'll close this issue
